name = "benamotors-11"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cars-db"
database_id = ""

[vars]
# Add any environment variables here if needed
