backend:
  name: github
  repo: soltana11/website-voitures-0
  branch: main
  auth_endpoint: api/auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "vehicles"
    label: "Véhicules"
    folder: "_data/vehicles"
    create: true
    slug: "{{name}}"
    format: "json"
    fields:
      - { label: "Nom du véhicule", name: "name", widget: "string" }
      - { label: "Année", name: "year", widget: "string" }
      - { label: "Kilométrage", name: "km", widget: "string" }
      - { label: "Prix", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
